### ISSUE TITLE
如果vc之间的参数是block类型的，该如何使用呢？

### ISSUE THREAD

**Issue by zengfxios** [casatwy/CTMediator#1]
如题

**Comment by casatwy** [comment]
block本质上也是一个对象啊，跟传普通对象的方法没区别啊。而且demo里也有传block的例子啊。

发自我的 iPhone

在 2016年10月17日，11:16，zengfxios <notifications@github.com<mailto:notifications@github.com>> 写道：


如题

―

**Comment by LKTheMaster** [comment]
category中传入一个block作为params中的一个value,但是target是swift的,如何将oc的block转成swift的closure?
