### ISSUE TITLE
在demo中，如果cell是自定义的，并且通过delegate的方式传递给外界，那应该怎么处理？

### ISSUE THREAD

**Issue by zhenshengLinGit** [casatwy/CTMediator#10]
由于TableViewController并没有依赖于Cell，所以TableViewController无法直接成为cell的delegate。那么如果cell想要进行传值的话，那么只能由Target_A来成为cell的delegate，那Target_A应该怎样将值传递给TableViewController进行处理呢？（使用NSNotification貌似有点多余）

**Comment by jiaopen** [comment]
这是个组件化方案，你的问题是组件内的事件传递，和这个方案无关

**Comment by casatwy** [comment]
没看懂你这个问题的描述？能给个具体的业务场景么？
