### ISSUE TITLE
请教下问题！

### ISSUE THREAD

**Issue by FrankCYQ** [casatwy/CTMediator#11]
目前正在研究您的组件化开发方式，但是遇到一个问题，就是我再businessA中用到的MediatorB， 在businessB中用到了MediatorA，然后我再demo中引入了这两个 businessA、businessB，工程就无法编译通过，麻烦大神帮忙指导下

businessA（依赖了MediatorB,通过分类调用了B业务的方法） 、businessB（依赖了MediatorA,通过分类调用了A业务的方法） 、MediatorA(依赖CTMediator)、MediatorB(依赖CTMediator) 都是单独的pod库
把  pod 'BusinessB', '~> 0.4.0'
  pod 'BusinessA', '~> 0.7.0'
这两个一起引入后工程就报错：Apple Mach-O-Linker Error

单独使用就没错~~

**Comment by casatwy** [comment]
具体报错的内容是什么？按道理在主工程引入双方business是没问题的
