### ISSUE TITLE
Target返回的类型不能是BOOL类型

### ISSUE THREAD

**Issue by glary** [casatwy/CTMediator#14]
EXC_BAD_ACCESS

**Comment by casatwy** [comment]
用最新版本的ctmediator就好了

发自我的 iPhone

在 2017年7月2日，下午2:19，Glary <notifications@github.com<mailto:notifications@github.com>> 写道：


EXC_BAD_ACCESS

**Comment by glary** [comment]
@casatwy 最新版本是6吗？我看CocoaPods/Specs  那是6的版本 你好像没推上去吧？

**Comment by casatwy** [comment]
现在到9了，应该推上去了吧？我在外面，回头看看。

发自我的 iPhone

在 2017年7月3日，上午11:29，Glary <notifications@github.com<mailto:notifications@github.com>> 写道：


@casatwy<https://github.com/casatwy> 最新版本是6吗？我看CocoaPods/Specs 那是6的版本 你好像没推上去吧？

**Comment by glary** [comment]
@casatwy   我搜到的还是6版本，好像没推上去

**Comment by casatwy** [comment]
确实。。。现在升到版本12了，我刚刚推上来了，你更新一下～
