### ISSUE TITLE
可以异步调用么？

### ISSUE THREAD

**Issue by bingFly** [casatwy/CTMediator#16]
比如在调用一个接口成功后才返回这个viewcontroller

**Comment by casatwy** [comment]
异步调用走block

发自我的 iPhone

在 2017年8月1日，下午6:41，bingFly <notifications@github.com<mailto:notifications@github.com>> 写道：


比如在调用一个接口成功后才返回这个viewcontroller

**Comment by bingFly** [comment]
源码里面- (id)performTarget:(NSString *)targetName action:(NSString *)actionName params:(NSDictionary *)params shouldCacheTarget:(BOOL)shouldCacheTarget
这个是没有block的，所以回调不了

**Comment by casatwy** [comment]
你看demo，params里面是可以塞bloxk的

发自我的 iPhone

在 2017年8月1日，下午6:51，bingFly <notifications@github.com<mailto:notifications@github.com>> 写道：


源码里面- (id)performTarget:(NSString *)targetName action:(NSString *)actionName params:(NSDictionary *)params shouldCacheTarget:(BOOL)shouldCacheTarget
这个是没有block的，所以回调不了

**Comment by bingFly** [comment]
你指的是这段代码么？
id result = [self performTarget:url.host action:actionName params:params shouldCacheTarget:NO];
    if (completion) {
        if (result) {
            completion(@{@"result":result});
        } else {
            completion(nil);
        }
    }
    return result;

还是在params:params这个params里面塞一个block参数？
麻烦你了

**Comment by casatwy** [comment]
你先仔细看demo？是通过category在params里面传block的。

发自我的 iPhone

在 2017年8月1日，下午6:57，bingFly <notifications@github.com<mailto:notifications@github.com>> 写道：


你指的是这段代码么？
id result = [self performTarget:url.host action:actionName params:params shouldCacheTarget:NO];
if (completion) {
if (result) {
completion(@{@"result":result});
} else {
completion(nil);
}
}
return result;

还是在params:params这个params里面塞一个block参数？
麻烦你了

**Comment by bingFly** [comment]
是这样的，demo里确实有通过方法调用有block回调的。现在我是在你的基础上统一通过url方式调用本地组件。所以才有了这个问题。现在通过url方式是没有异步执行的。是这个问题。

**Comment by casatwy** [comment]
可以这么做的

**Comment by casatwy** [comment]
我前面看错了。

你要用URL去做本地跳转？😂

我文章里面已经说得很清楚了，不要这么做。。。
