### ISSUE TITLE
项目跑不起来呢?

### ISSUE THREAD

**Issue by lafayea** [casatwy/CTMediator#17]
pod install 之后, 项目跑不起来, 提示:
ld: warning: directory not found for option '-L/Users/greatman/Library/Developer/Xcode/DerivedData/CTMediator-bmljppouvvqrztaquakdqpyyykij/Build/Products/Debug-iphonesimulator/HandyFrame'
ld: library not found for -lHandyFrame
clang: error: linker command failed with exit code 1 (use -v to see invocation)
好像是没有lHandyFrame这个东西...

**Comment by casatwy** [comment]
你pod install成功了吗？
