### ISSUE TITLE
Target与Category都用swift编写，不能跳转

### ISSUE THREAD

**Issue by linxyang** [casatwy/CTMediator#18]
您好，主要是方法那里不能识别出来。
```
// 有可能target是Swift对象
        actionString = [NSString stringWithFormat:@"Action_%@WithParams:", actionName];
        action = NSSelectorFromString(actionString);
        if ([target respondsToSelector:action]) {
            return [self safePerformAction:action target:target params:params];
        } else {
            // 这里是处理无响应请求的地方，如果无响应，则尝试调用对应target的notFound方法统一处理
            SEL action = NSSelectorFromString(@"notFound:");
            if ([target respondsToSelector:action]) {
                return [self safePerformAction:action target:target params:params];
            } else {
                // 这里也是处理无响应请求的地方，在notFound都没有的时候，这个demo是直接return了。实际开发过程中，可以用前面提到的固定的target顶上的。
                [self.cachedTarget removeObjectForKey:targetClassString];
                return nil;
            }
        }
```
上面这一断，进入到了else里面。

我的demo代码中，Target_Register.swift文件代码出下:
Target中代码如下:
@objc(Target_Register)
class Target_Register: NSObject {
    
    func Action_registerViewController(params: [String:Any]) -> XYJBaseVC {
        let vc = XYJRegisterVC()
        return vc
    }
}

category中代码如下:
//  1. 字符串 是类名 Target_xxx.h 中的 xxx 部分
let kCTMediatorTarget_Register = "Register"

//  2. 字符串是 Target_xxx.h 中 定义的 Action_xxxx 函数名的 xxx 部分
let kCTMediatorActionNavigaTo_RegisterVC = "registerViewController"

extension CTMediator {

    func ylx_mediator_registerVCWithParams(params: [String:Any]) -> XYJBaseVC {
        
        if let registerVc = performTarget(kCTMediatorTarget_Register, action: kCTMediatorActionNavigaTo_RegisterVC, params: params, shouldCacheTarget: false) as? XYJRegisterVC {
            
            return registerVc
        } else {
            // 这里处理异常场景，具体如何处理取决于产品
            return XYJBaseVC.init()
        }
        
    }
}

**Comment by casatwy** [comment]
https://github.com/ModulizationDemo/SwfitDemo

你看一下这个demo

**Comment by linxyang** [comment]
我是看你这个demo写的，你swiftDemo中，pod下的，A_category文件夹下用的还是oc分类实现，我用的是swift扩展，就这点一不一样。字符串转swift方法时，识别不了方法导致。

**Comment by casatwy** [comment]
那不应该啊，只要能调到CTMediator，就无所谓是通过swift还是oc。你把Demo拉下来跑跑看，Demo能能在你这边跑通？

**Comment by linxyang** [comment]
可以的，我把您的swiftDemo中的CTMediator+A分类替换成swift的Extension，一样效果。您有时间的话可以试试。
```
extension CTMediator {
    
    public func showViewController() -> UIViewController {
        return performTarget("A", action: "ViewController", params: nil, shouldCacheTarget: false) as! UIViewController
    }
    
}
```

**Comment by casatwy** [comment]
如果这样的话，那我觉得就没必要category也用swift写了，毕竟category只是针对调度的封装，跟业务没有任何关系。

**Comment by Jing2684** [comment]
大佬好，我看了你的demo,我删除了你的CTMediator分类和控制器分类，通过向CTMediator中传入目标控制器，方法名，及方法参数（不定多个），也可以实现本地的跳转（远程的没有考虑），主要是通过对invocation设置argument实现，没有调用最后的performSelector,感觉这样更简洁啊，不知道有没有什么潜在的问题，目前只是写了demo

**Comment by linxyang** [comment]
@casatwy 恩  谢谢解答！

**Comment by casatwy** [comment]
@Jing2684 因为参数数量是不定的，所以我才设计了参数只有一个dictionary的做法，所有实际业务参数都塞入dictionary传过去。

**Comment by Jing2684** [comment]
谢谢回复，邮件直接回复你的，不知道你能否收到，邮箱看你的回复显示不完整，这里才完整看到你说的

**Comment by casatwy** [comment]
@Jing2684 我收到了

邮件的内容是我写的第一版回复，你这里看到的是我写的最后一版回复
