### ISSUE TITLE
CTMediator源码疑问

### ISSUE THREAD

**Issue by GDAwen** [casatwy/CTMediator#19]
casa老师，你好；

CTMediator类中方法有个疑问，target中有些方法是不需要参数的
performTarget:(NSString *)targetName action:(NSString *)actionName params:(NSDictionary *)params shouldCacheTarget:(BOOL)shouldCacheTarget中
下面这两行代码就不是很合理了
NSString *actionString = [NSString stringWithFormat:@"Action_%@:", actionName];

actionString = [NSString stringWithFormat:@"Action_%@WithParmas:",actionName];

我觉得“:” 写到Mediator的category中最actionName的声明中，
如 NSString * const kCTMediatorActionNativFetchDetailViewController = @"nativeFetchDetailViewController:";
这样是不是合理一些？

这样的话，在performTarget:(NSString *)targetName action:(NSString *)actionName params:(NSDictionary *)params shouldCacheTarget:(BOOL)shouldCacheTarget方法中，需要针对action是否是带参数进行区分  [target performSelector:action];

**Comment by casatwy** [comment]
1. 因为selector加冒号是iOS特有的需求。

所以，在针对H5做跳转，或跨App跳转时，Android和JS那边的实现使得加冒号没有意义。

2. 因为我倾向于为未来保留拓展性。

所以设计的时候默认所有的方法都带参数，且只带一个参数，且这个参数一定是dictionary。当这个方法不需要参数就能执行的时候，参数传nil，将来需要添加参数的时候，无论之前是否需要传参数，方法的声明都无需改变。

3. 因为我倾向于保持设计思路的一致。

如果不能保持设计思路的一致，就会导致使用者额外付出甄别的成本。所以如果有的方法需要冒号，有的方法不需要冒号，就会额外增加使用者需要确认方法是否需要带冒号的成本，这个成本其实用现在的实现方式来看，是没有必要的。

4. 因为有category做跳转中介，通过阅读category给到的调用声明，参数本身就能够得到很好的管理。

在我的设计里，所有的跳转都不是直接走CTMediator的performTarget：Action：Params方法的，都是通过CTMediator的category来做参数收集、整理、target-action调度的操作。当一个工程师需要调度一个需要参数的target-action，工程师通过category就能够清晰地知道这些参数有哪些，分别是哪些类型。如果这个target-action是不需要参数的，category方法也不会被声明成需要参数的调度。在这种情况下，CTMediator的perform方法这一层级根据参数来做区分，是没有意义的，反而增加了CTMediator实现的复杂度。

**Comment by GDAwen** [comment]
好的，谢谢casa老师的解答，我再去看几遍源码，多揣摩下
