### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by qingxuluo** [casatwy/CTMediator#2]
Class targetClass = NSClassFromString(targetClassString);
    id target = [[targetClass alloc] init];
    SEL action = NSSelectorFromString(actionString);
这样不是每perform一次都会新生成一个target,调多了内存怎么管理

**Comment by casatwy** [comment]
在高频调用的场景下，程序是不会频繁执行开辟内存的操作的，而是从现有已开辟的堆中新划内存，性能损失不会很大。

另外，高频调用在一个app的使用期间出现的频率极低，不值得为它单独hold住内存。这其实是属于内存使用的一个极端场景，如果业务上真有高概率的高频调用，那么才需要特事特办。

最后，建议这类似的问题可以在文章下面的评论区问。评论区翻墙就有了。

发自我的 iPhone

在 2016年10月18日，14:24，qingxuluo <notifications@github.com<mailto:notifications@github.com>> 写道：


Class targetClass = NSClassFromString(targetClassString);
id target = [[targetClass alloc] init];
SEL action = NSSelectorFromString(actionString);
这样不是每perform一次都会新生成一个target,调多了内存怎么管理

―
