### ISSUE TITLE
是否考虑让用户自己处理无响应请求？

### ISSUE THREAD

**Issue by Doramical** [casatwy/CTMediator#22]
发现升级到swift 4.0之后，重新更新后引入了`CTHandyCategories`，查看源码就是处理无响应请求的时候弹出一个alertview。对于稍微有点代码洁癖的码农来说，不希望引入额外的代码文件~
#####建议让用户自己处理无响应的情况，改进如下：
``` objective-c

typedef id(^NoTargetActionHandler)(NSString *targetName, NSString *actionName)

@interface CTMediator : NSObject

@property (nonatomic, copy) NoTargetActionHandler handler;

@end
```
然后使用`handler`替换掉`[self NoTargetActionResponseWithTargetString:targetClassString selectorString:actionString];`，这样可以去掉对`CTHandyCategories`，同时也可以让用户自己处理无响应的情况。

**Comment by casatwy** [comment]
嗯，说得有道理。

只不过给CTMediator添加一个属性的方法我不觉得好。

因为在组件化场景下，CTMediator会在很多个不同的组件中使用。如果需要在每次单独运行每个组件的时候都能够检测出未响应的target-action，就需要在每个组件里面都写一遍这个block。

所以，我的改法会是这样：

在未响应Target-Action的时候，固定去调`Target_NoTargetAction`中的`Action_response:`。把这个target-action做成组件，在需要调试的组件里面引入就好了。

**Comment by casatwy** [comment]
已经更新了
