### ISSUE TITLE
关于单例model的使用问题

### ISSUE THREAD

**Issue by zramals** [casatwy/CTMediator#24]
尊敬的作者你好，
我想问一下，如果平台有类似于userManger这种单例对象，各业务线想要获取该对象应该怎么处理？
该对象拥有一些user属性，另外还会存在多种类似于register,clear的方法，业务方可能需要调用[UserManger shareManager].userName或[[UserManger shareManager] register]。
其中方法可以category映射出来，属性也可以写一个get方法通过字典传出来。
我想请问的是，在实际使用中有没有更好的方法？

**Comment by casatwy** [comment]
没有更好的方法了

**Comment by sytuzhouyong** [comment]
可以用 __attribute__ used section 这种类似于快速配置表的功能来实现

**Comment by Tiaotiaotiao** [comment]
> 没有更好的方法了

好吧 我也需要这种的情况 😭
