### ISSUE TITLE
有一种使用场景

### ISSUE THREAD

**Issue by MountainHill** [casatwy/CTMediator#25]
你好，目前应用中有这样一种使用场景：
模块A中有个广告业务，广告有很多中接口，但最终都能转成一种view model
现在有模块B,它想通过路由使用A模块提供的广告功能，界面稍有不同，view model可以共用，那我如何通过target-action这种形式的路由实现这种场景呢？

**Comment by casatwy** [comment]
如果用户在View上有交互需要响应，把响应的代码写成block，让B塞到字典里当成数据传过去，A的target生成ViewModel的时候，把block也带上。

最终B还是只需要展示UIView即可。

**Comment by MountainHill** [comment]
你好，感谢你的回答，我的表述有问题让你产生了歧义。
问题是这样的，一开始先有模块A，A中有一个广告业务，这个广告有一整套逻辑（比如数据的校验去重...）,现在新增了模块B，B需要使用A的广告业务，界面目前不打算复用，只要用到A模块中广告的逻辑处理这一层，即B模块是需要知道A模块处理广告最终生成的view model的类型，这就跟target-action中只能传dictionary产生了矛盾。
当然我承认模块间的耦合越少越好，但有时为了复用又不得不知道其他模块中的类，这个我觉得很矛盾。

**Comment by MountainHill** [comment]
补充：
即B模块是需要知道A模块处理广告最终生成的view model的类型
----A模块和B模块的界面稍有不同，但view model可以共用，所以B需要知道A模块处理广告最终生成的view model的类型

**Comment by casatwy** [comment]
B拿到ViewModel之后，做什么事情？

**Comment by MountainHill** [comment]
B拿到view model后给view B做界面渲染

**Comment by casatwy** [comment]
这种情况应该做一个“广告View工厂”，A和B都从这个工厂拿广告。

这个工厂能够生产A可以用的广告，也能够生产B能够用的广告。只需要在调用的时候告知工厂生产什么广告即可。

**Comment by MountainHill** [comment]
但做A模块的时候并不知道有B模块，B模块也是刚加的，同时在可预见的期限内（如半年）是不会新增View C的，并且若做成工厂，那工厂由谁维护呢，我还是倾向不做工厂，由各自的模块去维护他自己的view.
我想复用A的广告view model，比如我如果用protocol-class形式的路由就可以解决这个问题，但这种模式的路由又是你不推荐的，所以我就有了这个问题。

**Comment by casatwy** [comment]
现在主要是想让ViewModel的声明被其他业务知道。于是这种情况就导致了命名域渗透的问题，也就是A和B这两个业务之间需要互相知道对方，也就是存在依赖关系。

所以为了解决这个问题，还是需要工厂来把生产View的事情做掉，这样A和B就独立出来了。

A和B之间独立出来有两个好处，一个好处就是你说的，如果将来有C，那么新增一下很方便。另一个好处就是A和B在未来的迭代中如果有改动的话，只要改工厂就可以了。

这对项目来说条理比较清晰。

**Comment by casatwy** [comment]
工厂就是把A原来的逻辑抽出来，然后再新增一个B需要的逻辑。由谁维护不重要，因为将来不管是谁维护，工厂都很容易维护，这次写好，放着不管就行了。

**Comment by MountainHill** [comment]
1. 也就是A和B这两个业务之间需要互相知道对方
----不是的，实际情况是A不需要知道B，而是纯粹的B依赖A

2. 工厂就是把A原来的逻辑抽出来，然后再新增一个B需要的逻辑。由谁维护不重要
----由谁维护很重要，组件化的目的有一点就是清晰的划分责任人

我不赞成做成工厂模式，一是没有任何必要，二是我觉得工厂模式不是这么用的

解决这个问题，目前我能想到的有2种，一种是protocol-class路由形式，第二种是让A将view model做成一个subspec，B依赖这个subspec，这两种方式B都需要显示的知道A中view model类的存在，只是第一种因为具备路由属性，有点冲突，第二种作为依赖知道A中view model类的存在无可厚非。

**Comment by casatwy** [comment]
1. 我说得确实不严谨，但对于A，B这两个平行业务来说，B依赖A也是不好的实现。

2. 由谁维护不重要，组件化的目的没有“清晰划分责任人”这一点。但组件化有一个主要目的是为了降低工程的维护成本。

降低了成本之后，我们是希望谁都可以来维护这个组件。如果专人维护，反而会导致单点问题。这是其一。

其二是，组件化程度高的工程，组件数量有上百个。我目前的电商App，组件有279个。但我们只有7个iOS工程师。每个迭代过程中，涉及的组件很少超过10个。所以在每个迭代分配任务的时候，不会按照哪个组件归谁维护去分任务的，而是把任务拆解成差不多的工作量，然后再分下去。每个人并不会固定维护几个组件。让每个人去固定维护某几个组件是不现实的。

其三，由于每个人都接触过不同的组件，任何一个人请假、离职都不会产生单点问题，交接速度极快，上手成本极低。

所以“组件化的目的有一点就是清晰的划分责任人”是一个误区。

最后，做广告View逻辑的抽象是很重要的，通过工厂模式，A和B可以完全隔离独立运行。将平行业务作隔离并能够独立运行，也是组件化的目标之一。

**Comment by casatwy** [comment]
所谓的维护，无非就是两种情况导致：

1. 出Bug了要修
2. 来需求了要改要做

当没有bug，且迭代任务不涉及某组件的时候，该组件是没有“维护”的工作量的。所以指派维护人也是不现实的。

**Comment by casatwy** [comment]
你这一轮迭代中，如果设立了工厂，下一轮迭代如果不涉及工厂组件，那你维护工厂组件的人就没必要做事情。

下一轮迭代如果涉及工厂，那也不必跑到B业务或者A业务里面改来改去，直接改工厂就好了。

**Comment by MountainHill** [comment]
我们是希望谁都可以来维护这个组件。如果专人维护，反而会导致单点问题。这是其一。
由于每个人都接触过不同的组件，任何一个人请假、离职都不会产生单点问题，交接速度极快，上手成本极低。
----这个在我们的项目组是不现实的，目前我们项目组有20多个iOS开发，有外包人员，有新进来的员工，有做事敷衍的人员，当然也有做实事的人，鱼龙混杂，水平不一，尤其是有些历史业务已经发展了多年了，是没法做到谁都能快速修改的。所以我采取的策略就是先把责任划清晰，以杜绝推诿扯皮(因为有的人每次一来bug就说不是我的，即使bug明确能看出是他的)。
这是目前我们项目组中的一些情况，鉴于这种情况，你还觉得“所以“组件化的目的有一点就是清晰的划分责任人”是一个误区。”吗？

**Comment by casatwy** [comment]
git blame在那里，谁写的代码一目了然。这种情况下谁出的bug那就谁改啊～如果写这个代码的人离职了，那你就指派一个人去改啊。他如果不听话么，这一季度KPI应该就别想要了吧。

而且在迭代内，你分配出去的任务都是明确到个人的。涉及某个业务的bug，就应该是迭代内负责这个任务的人去修改这个bug。如果代码不是他写的，是别人写的，那也应该是他自己去找当初那个人请教这部分代码是怎么回事才对啊。

总之，组件化的目的不是为了划分责任人，因为责任人很有可能离职休假升职。组件化的目的是为了降低维护成本，让每个人拿到这个任务都能找到对应的组件去做修改或迭代。

就实践上看，对于未来能够最低成本维护你当前情况的做法，就是创建一个工厂。

然后你把创建这个工厂的任务交给一个人去做。但凡这个迭代内出的bug，就都是这个人去做。下一个迭代如果还涉及工厂，你可以选择还把这个任务交给他，不过我建议是换人去做，让每个人都熟悉不同的业务，这样任何一个人离职，你作为teamleader，都能迅速找到人顶上。

这才是正确的leader应该做的事情。

**Comment by casatwy** [comment]
如果责任人离职休假升职，代码出问题了，你这边短时间内没人能顶上，这才是大事。

**Comment by MountainHill** [comment]
那如果做个工厂F，那A，B是不是都要依赖这个F？
PS:我是没有KPI考核权的，同时我也不是leader，我也是搞架构的，只是看到项目组的一些问题。

**Comment by casatwy** [comment]
A和B不需要依赖F，只要给到F_category即可，category收集参数，然后给到target-action让CTMediator去调度F的target.

**Comment by casatwy** [comment]
A和B都可以在没有F的情况下独立编译运行。且podspec只需要F_category，不需要依赖F，Podfile里面给到F就可以了。

**Comment by MountainHill** [comment]
根据你的建议，F_category应该定义一个方法
```
- (UIView *)getAdView:(NSEnum)type;
```


但是如果我定义
```
- (AdViewModel *)getAdViewModel;
```
这样以后增加模块C,D该方法不是不用改么？反而上面的需要增加C/D的view

**Comment by MountainHill** [comment]
A/B/C/D依赖的是view model,需要完成的是各自模块的view,用工厂返回各种view是不是把本该属于A/B/C/D的视图业务揉进了不变的view model组件?
写view model组件的人其实完全不需要知道A/B/C/D模块中广告视图长啥样

**Comment by casatwy** [comment]
你用上面的方法，即使增加C和D，原有的代码也不用改啊。

新增C和D的操作就只是增enum而已，这又不是强业务。

你用下面的方法不是命名域泄漏了么，你还需要其他组件引入viewmodel的声明，这就是强业务了，没有必要啊。

**Comment by casatwy** [comment]
你C和D的view工厂负责生产了，业务只要告诉工厂要什么view就好了，业务为什么还要关心用什么viewmodel呢？

你最终目的是为了展示view啊

**Comment by MountainHill** [comment]
补充下，严格意义上说应该不能叫view model，实际是这样的
![20180522171247149](https://user-images.githubusercontent.com/7063621/40353233-91b15eec-5de3-11e8-944e-08fc27cb53ce.png)

**Comment by MountainHill** [comment]
工厂生产view,那工厂不就需要知道A/B/C/D使用什么样的view么？那这个工厂放哪呢？

**Comment by MountainHill** [comment]
我本意是view各个模块自己去创建，这样我这个模块删了，不用动其它的代码

**Comment by MountainHill** [comment]
你还需要其他组件引入viewmodel的声明
----如果采用我说的方式，确实需要引入

**Comment by casatwy** [comment]
1. CTMediator是走的runtime调度，所以只要podfile里面引入工厂pod就行，业务是不需要在podspec里面写工厂pod依赖的。这个明白吧？

2. 你说的对，但不完全对。其实工厂不需要知道哪个业务用哪个View，工厂只需要知道哪个enum对应要生产哪个view。跟业务无关。

3. 创建view的过程是可以抽出来放到工厂的，业务只管自己的业务流程即可，完全没必要关心view是怎么生产的。

而且将来如果你其他的业务需要复用广告view，那也是给type就行了。假设你的type分为XXX_topBar,XXX_bottomBar,xxx_wholePage，这样将来其他的业务如果要挂广告，根据type问工厂去拿就可以了。

在复用的场景下，如果有其他业务组件复用了你B的广告view，然后这个迭代产品跟你说B不需要了，那你不还是得要把这个生产流程拎出来？拎出来的流程那么费劲，干嘛不直接一开始就独立做好？

**Comment by casatwy** [comment]
viewModel只是你的流程的中间产物，你需要对整个流程做抽象。这样架构的条理才清晰。

**Comment by casatwy** [comment]
你前面的架构图设计逻辑有问题，业务应该只负责自己的业务流程。比如1号位置放A类广告，2号位置放B类广告。

业务不需要自己生产广告，应该是在需要A类广告的时候，告诉工厂我要A类广告。需要B类广告的时候告诉工厂我要B类广告。这样将来不管是维护广告，还是维护业务，都很轻松，没有耦合。广告的复用、点击的后续处理，工厂都能搞定。

业务应该是只管问工厂拿广告然后放上。

**Comment by MountainHill** [comment]
1. CTMediator是走的runtime调度，所以只要podfile里面引入工厂pod就行，业务是不需要在podspec里面写工厂pod依赖的。这个明白吧？
----这个肯定明白啊，这也不是我要问的问题

2. 工厂只需要知道哪个enum对应要生产哪个view。跟业务无关。
----这个需求都是业务的，怎么可能工厂不需要知道呢？如果工厂不需要知道，那如果A模块说我的按钮要从左边调到右边，工厂生成的view要不要改?

**Comment by casatwy** [comment]
1 我就不说了。

2. 按钮在左边的广告和按钮在右边的广告，那就是不同的enum了啊。A业务只要传按钮在左边的广告的enum给工厂就行了。或者category再多给个接口告诉工厂按钮在左边还是在右边。

工厂模式你应该懂吧？工厂模式完全不需要知道自己生产的产品需要用到哪里，把需求告诉工厂，工厂生产出来就交出去。至于交给谁，工厂无所谓啊

**Comment by MountainHill** [comment]
你前面的架构图设计逻辑有问题，业务应该只负责自己的业务流程。比如1号位置放A类广告，2号位置放B类广告。
----这个设计没有问题的，确实是有各种类型的广告，前面设计图中有3种request,问题是这3种广告返回的数据结构一模一样，难道我要设计3个一模一样的类型？

**Comment by MountainHill** [comment]
把需求告诉工厂
----对啊，这个需求就是各模块的需求啊，如果用工厂，那是不是界面上稍微改下，工厂就要添加参数以应对?

**Comment by MountainHill** [comment]
工厂模式你应该懂吧？
----工厂模式我用过一点，确实不是很懂，我的理解是有些东西生产的比较费劲，又比较固定，那就让工厂给我生产

**Comment by casatwy** [comment]
如果你这个迭代的广告view，按钮在左边，那么你工厂对应的这个enum就生产按钮在左边的view。

如果你下个迭代的广告view，按钮在右边，那么你工厂对应的这个enum就改成生产按钮在右边的view。

如果你下个迭代是新增了按钮在上面的广告view，那你要么新开一个enum，告诉工厂按钮在哪儿，工厂就生产按钮在哪儿的view。

--------

3种广告3种request没问题啊，收到response的时候你是知道这个response对应哪个request的啊。然后你拿到response，再根据request是哪个，决定传给工厂的enum是哪个就好了，工厂就根据你给的enum和response data去生产广告了。

--------

各模块有各模块的需求没错，界面稍微改下，分两种情况：

旧的界面不要了，用新的界面：那就直接在同一个enum下面改view

旧的界面也要，新的界面也要：那就开个新的enum生产新的view咯

不管你用不用工厂，修改的代码是少不了的。但你不用工厂，这部分代码就会放在也无力，如果你用了工厂，这部分代码就会放在工厂里。这很明显应该放在工厂里啊。

**Comment by casatwy** [comment]
工厂模式封装的是对象生产流程，跟固定与否无关。

如果你要生产的东西不固定，你把生产流程放在业务里，因为这个东西不固定，人家业务就要改来改去去适应这个东西的改变，这就导致了你的业务流程跟生产流程耦合，业务方改这部分代码很讨厌的啊。但如果你放在工厂里，这个东西变来变去，你只要改工厂就好了，跟业务流程无关，一方面很容易改，另一方面你怎么改都不会影响业务，这多好。

如果你要生产的东西是固定的，你把生产流程放在业务里更加是没必要了啊，万一别的业务也需要这个东西，它要么自己重新写一遍，要么就是依赖你现有业务，这两者都不可取啊。如果你放在工厂里，业务就不需要依赖业务了，直接问工厂拿就好了啊。

**Comment by MountainHill** [comment]
我说的固定的意思是不会经常变来变去，比如NSNumber,就那么几种类型，在可预期的时间内不会经常变动。

你这个广告组件是单独的pod吧，界面如果需要修改，那么广告组件就需要重新打tag发布，然后相关模块再update调试，而如果view本来就在模块里面构造，广告pod压根就不需要更新

**Comment by MountainHill** [comment]
我想我大概理解了你的意思，但我的意思是让需要变动的就让它变动，只固定不需要经常变动的

**Comment by casatwy** [comment]
对，如果你把生产的流程放在业务里面，修改了之后，你确实不需要更新工厂pod了，但你需要更新业务pod啊，但你又不能改完之后立刻更新业务pod，因为业务pod还有很多其他的东西正在开发啊。

如果你把生产流程放在工厂pod了，那你更新了之后，就只需要更新广告pod就好了，完全不用关心业务现在开发进展到哪儿了。然后你工厂扔出来的是UIView，业务只是把UIView贴上去，说白了就是一句addSubview。业务的这部分操作怎么写都不会出bug啊～而且你广告pod自己也可以测试不同的view在不同的布局下是不是你想要的结果，这个测试也是完全跟业务无关的。

--------------

“让需要变动的就让它变动，只固定不需要经常变动的” 我的point在于，不管它是不是变动，你抽出来放到工厂里，变动也好不变动也好，做修改做测试都很容易，也不会影响到业务，也不需要关心业务。

**Comment by MountainHill** [comment]
但你需要更新业务pod啊
----是要更新业务pod，但我可以在当前业务pod下更改验证，后面更新打包都是机器做的，不用依赖工厂的pod更新

不管它是不是变动，你抽出来放到工厂里，变动也好不变动也好，做修改做测试都很容易，也不会影响到业务，也不需要关心业务
----这个所谓的不需要关心业务其实是伪的，如果业务方不给你实际的ui，该组件的编写者是无法测试验证的，放到工厂无非是把属于业务方的业务移到该组件方，这样解决组件间调用不用传model的问题

业务ui是恒变的，为何要把一个恒变的东西给一个基本不变的组件呢？

我觉得protocol-class这种没有问题，虽然会涉及model的导入，但可以再定义一个model专供protocol用，类似一个中间model，这样也不算入侵业务方，我之前一直陷入组件化不能传model的误区，为何不能传model呢？只要能保持接口的稳定就行，难道UIImage不是model吗？只是它是系统的model罢了。

感谢跟你的讨论，架构无常法，只要做到复用，稳定，可扩展，易测试就可以，你有你的方法我有我的方法，可能你的方法是好的，我现在能力有限无法理解，后面我碰到问题了才知道你是对的，但架构不也是一个不断试错迭代的过程么，就像没有人能做到前面有坑就一定不踩一样。

再次感谢你的耐心解答和及时的交流。

**Comment by casatwy** [comment]
@wjacker 

你的protocol主要是用于delegate回调，引入protocol就意味着引入一个pod。一旦引入了一个新的pod，组件化的其中一个目的就无法完成：隔离依赖。

因为既然你引入了一个pod了，那为什么还要走组件化调度去执行任务呢？直接使用pod的对象就可以啦。

对于你的情况，正确的做法是把回调封装成block。category通过函数参数接收到block之后，把block作为字典value塞入params中传递过去。

在target-action中将block取出，交给需要执行回调的对象，在这个对象中执行block，就完成回调了。

这种做法就在完成回调的同时，避免了引入新的pod。

**Comment by wjacker** [comment]
@casatwy 谢谢回答，你说的这种我也有想过，但是感觉这种实现起来会比较麻烦，尤其在已经存在的项目中，改的话可能需要吧之前的哪些delegate的地方都改成block的回调，而且调用的地方如果有对象的话，都需要改成字典key value的形式，对于调用来说调用的方式挺麻烦的，一大堆的key value 调用方未必知道都需要哪些key 以及key的含义，还有一种改法就是在category里边单独加一些对外的model跟protocol, 调用方使用这些model/protocol 传入，然后在category里边调用的时候在把这些转成转成字典传给对应的model. 相当于多创建一了些重复的model/protocol，好处是简化了调用方的代码（去除了字典key/value），不太好的就是增加了一套中间的对象跟protocol。

**Comment by wjacker** [comment]
另外对于delegate的貌似也只能用block传入了，但是总感觉改动量会比较大，因为目前我们的项目几乎全部都是通过delegate 去做的回调

**Comment by casatwy** [comment]
关于delegate的改动，其实也不大，category给到这样的方法就可以了：

`- (void)showAlertWithMessage:(NSString *)message cancelAction:(void(^)(NSDictionary *info))cancelAction confirmAction:(void(^)(NSDictionary *info))confirmAction;
`
这些其实在我的demo里面都有的

**Comment by casatwy** [comment]
而且delegate和block两者不冲突，你完全可以这么做：

```
if ([self.delegate respondsTo:@selector(callback:)]) { [self.delegate callback:result]; }

if (self.callback) {self.callback(result);}
```

这两个本来就不是冲突的事情，它造成的改动不会引入bug

**Comment by wjacker** [comment]
如果category给到的是- (void)showViewControllerWithUserid:(NSString *)userId shopName:(NSString*)shopName这种方法，其实就完全没必要再去声明一个model或者protocol了。

嗯 对于model属性较少，写成方法是没问题的，但是对于model属性比较多的情况，改成方法 岂不是导致方法会很长。。。

**Comment by casatwy** [comment]
假设你要展示一个商品详情页，那么这个页面需要很多数据才能渲染完成。这虽然看上去必需参数有很多，但实际上你只要给到一个商品ID就足够了，让商品详情页自己去根据商品ID调API去获取数据。

所以从实际场景出发，如果出现了需要很多数据才能调用的情况，这个在设计角度上就是有问题的。你需要做的事情就是搞清楚真正的必要条件都有哪些，而不是抱着无所谓的态度把一堆东西给到就算OK了。

这套流程设计思路的重点不在于怎么把model给传过去，转成字典还是给到protocol？这时的思路方向已经不对了。正确的思路应该是`怎样提高被调用模块的集成度，使得仅需要满足最少的充要条件，就可以唤起一个流程`。

**Comment by casatwy** [comment]
因为你组件化的真正目的是为了调度业务，而不是传递model

**Comment by wjacker** [comment]
因为你组件化的真正目的是为了调度业务，而不是传递model
--
嗯 确实，一语道破 👍
