### ISSUE TITLE
在workspace里找不到target

### ISSUE THREAD

**Issue by YaoJuan** [casatwy/CTMediator#26]
我没有用私有pod去分离组件，而是每个组件对应一个单独的project放在workspace里。很好奇为什么这样在其他类里执行的时候会初始化target不成功，targetClass地址也没有是0X0.只有当我把子组件里的对应的Target_XX.h暴露在需要调用的其他组件，并且初始化一个对象的时候才能在您的库里初始化成功。而且试了试我如果只导入这个.h，没有初始化也无法初始化成功,必须得和下图一样手动调一下才行。是我有什么操作不当的地方吗
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    Target_Index *target = [Target_Index new];`
    UIViewController *vc = [[CTMediator sharedInstance] index_viewControllerWithTitle:@"测试"];
}

**Comment by casatwy** [comment]
应该是配置问题吧，这个我不确定。原因应该是runtime启动加载对象的时候，别的project的对象没能被加载进去。

**Comment by huangjianke** [comment]
@YaoJuan @casatwy 
同样的问题，有解决方案么

**Comment by casatwy** [comment]
把代码贴上来看看吧

发自我的iPhone

在 2020年4月7日，23:46，Jianke Huang <notifications@github.com> 写道：

﻿

@YaoJuan<https://github.com/YaoJuan> @casatwy<https://github.com/casatwy>
同样的问题，有解决方案么

**Comment by huangjianke** [comment]
@casatwy 配置问题，主工程加上 -ObjC 就可以了，谢谢
