### ISSUE TITLE
iOS 9.1-9.x系统，return [target performSelector:action withObject:params]; 在此处crash

### ISSUE THREAD

**Issue by Bofearless** [casatwy/CTMediator#27]
参数，target都正常，已进入对应的SEL，执行完成之后，crash在此处：

**Comment by Bofearless** [comment]
if ([target respondsToSelector:action]) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Warc-performSelector-leaks"
        return [target performSelector:action withObject:params];
#pragma clang diagnostic pop

**Comment by casatwy** [comment]
看不到图片？

**Comment by casatwy** [comment]
crash信息是什么？

**Comment by Bofearless** [comment]
![image](https://user-images.githubusercontent.com/16445320/41645768-84c869a0-74a4-11e8-9b1e-d7fd2224259e.png)

@casatwy

**Comment by Bofearless** [comment]
![image](https://user-images.githubusercontent.com/16445320/41645875-dbdfa9ba-74a4-11e8-9d83-3bb5028fbbda.png)

@casatwy

**Comment by casatwy** [comment]
你完整的调用是怎样的？

发自我的 iPhone

在 2018年6月20日，16:13，Bofearless <notifications@github.com<mailto:notifications@github.com>> 写道：


[image]<https://user-images.githubusercontent.com/16445320/41645875-dbdfa9ba-74a4-11e8-9d83-3bb5028fbbda.png>

@casatwy<https://github.com/casatwy>

**Comment by Bofearless** [comment]
我这里目前使用的是 WKWebView与JS交互时，使用CTMediator来找到工程中对应的的target和action来执行具体实现。

代码顺序截图如下：
WKScriptMessageHandler回调，调用[CTMediator sharedInstance] performTarget：
![image](https://user-images.githubusercontent.com/16445320/41648123-a712dc2e-74aa-11e8-812d-397f7f1db98b.png)

进入此方法：
![image](https://user-images.githubusercontent.com/16445320/41648355-3bba09ce-74ab-11e8-9205-2c06a9a667d9.png)

继续进入我的action，执行完函数里的代码：
![image](https://user-images.githubusercontent.com/16445320/41648382-4a87390e-74ab-11e8-8f72-27400b83db7a.png)

然后会回到这里，就在这里crash了：
![image](https://user-images.githubusercontent.com/16445320/41648418-6872eca6-74ab-11e8-9fff-4a8e8bc83b42.png)

**Comment by casatwy** [comment]
是dispatch_after导致的内存过早回收，因为target没有被hold住。建议调度的时候shouldCacheTarget设置为yes，然后整个流程结束之后再clean这个target。

发自我的 iPhone

在 2018年6月20日，17:01，Bofearless <notifications@github.com<mailto:notifications@github.com>> 写道：


我这里目前使用的是 WKWebView与JS交互时，使用CTMediator来找到工程中对应的的target和action来执行具体实现。

代码顺序截图如下：
WKScriptMessageHandler回调，调用[CTMediator sharedInstance] performTarget：
[image]<https://user-images.githubusercontent.com/16445320/41648123-a712dc2e-74aa-11e8-812d-397f7f1db98b.png>

进入此方法：
[image]<https://user-images.githubusercontent.com/16445320/41648355-3bba09ce-74ab-11e8-9205-2c06a9a667d9.png>

继续进入我的action，执行完函数里的代码：
[image]<https://user-images.githubusercontent.com/16445320/41648382-4a87390e-74ab-11e8-8f72-27400b83db7a.png>

然后会回到这里，就在这里crash了：
[image]<https://user-images.githubusercontent.com/16445320/41648418-6872eca6-74ab-11e8-9fff-4a8e8bc83b42.png>
