### ISSUE TITLE
swift项目 podspec里s.static_framework = true会报Target冲突

### ISSUE THREAD

**Issue by wateryys** [casatwy/CTMediator#28]
XXXX/Build/Intermediates.noindex/ZFMapModule.build/Debug-iphoneos/ZFMapModule_Example.build/Objects-normal/arm64/Target_MapModule.o
  XXXX/Build/Products/Debug-iphoneos/ZFMapModule/ZFMapModule.framework/ZFMapModule(Target_MapModule.o)

**Comment by wateryys** [comment]
当前的工程就叫ZFMapModule，可以试下建一个空工程，然后s.static_framework = true和创建一个Target也是冲突报错0.0，我的解决办法是用扩展，把Target写到BaseModule里去了，其他Target扩展它写。

**Comment by casatwy** [comment]
你的问题我无法重现，我觉得这并不是CTMediator的问题
