### ISSUE TITLE
Swift中NSClassFromString需要添加命名空间才能获得类

### ISSUE THREAD

**Issue by HQApe** [casatwy/CTMediator#29]
在Swift工程中
NSString *targetClassString = [NSString stringWithFormat:@"Target_%@", targetName];
targetClass = NSClassFromString(targetClassString);
targetClass 为nil，后面应该在取一次targetClassString = [NSString stringWithFormat:@"工程名.Target_%@", targetName];

**Comment by casatwy** [comment]
这个问题解决了，新版是25。

如果是swift调度的话，需要在params里加一个参数kCTMediatorParamsKeySwiftTargetModuleName, 然后给到module名字。

```
self.performTarget("MandarinUploadViewController",
                           action: "show",
                           params: [kCTMediatorParamsKeySwiftTargetModuleName:"MandarinUploadViewController"],
                           shouldCacheTarget: true)
```

**Comment by Yanemperor** [comment]
如果没有把module放到pod里面而是放在本地，kCTMediatorParamsKeySwiftTargetModuleName传入target名字，比如“SwiftDemo”
