### ISSUE TITLE
UI的组件化问题

### ISSUE THREAD

**Issue by LiuHangqi** [casatwy/CTMediator#3]
大神你好，看了你的iOS组件化方案，受益颇深，目前我也在对公司的项目进行组件化重构，现在遇到这个问题：
我觉得项目中的一些通用UI也应该作为一个组件存在，那么在使用UI组件的过程中，就免不了在对组件实例化之后进行赋值等操作，比如UITableViewCell，必然要在复用时进行赋值操作，而复用就意味着cell实例已经存在。在您的方案中，只能在获取实例的同时对实例进行操作，对已存在的实例却无能为力，我想请教下您针对这种情况有没有什么好的方案，谢谢

**Comment by casatwy** [comment]
这个问题建议在文章下面的评论区提问，issue里只回答CTMediator本身代码层次的问题。你的提问我一定会回答。
