### ISSUE TITLE
有多个target，并且多个target 的action功能是一样的，应该怎么处理？需要建立每个target对象吗

### ISSUE THREAD

**Issue by xunkaisummer** [casatwy/CTMediator#30]

**Comment by casatwy** [comment]
具体业务场景描述一遍？

我想知道为什么相同的功能会出现多个Target？

**Comment by xunkaisummer** [comment]
我们从服务器获取九宫格功能，然后展示点击进行本地跳转，可是服务器存在老接口，使用的target 不能保持一致，跳转时存在多个target

**Comment by xunkaisummer** [comment]
想做到target与action进行分离。

**Comment by casatwy** [comment]
不用care服务器给到的target是什么，你自己命名一个新target，叫做`Target_XXXProxy`。再定义一个`Action_dispatch:(NSDictionary *)params`。

然后再以服务端的target-action作key，对应响应做成Invocation，塞到名为strategy的字典里。

服务端所有的target-action全部走`Target_XXXProxy`的`Action_dispatch:(NSDictionary *)params`，在params里面根据服务端的target-action取到Invocation直接调用即可。

这样九宫格的所有数据就只走一个Target-Action，而且没有if-else语句。

**Comment by xunkaisummer** [comment]
谢谢，我先试试
