### ISSUE TITLE
swift使用CTMediator，target总为nil？导致闪退

### ISSUE THREAD

**Issue by DanielXinYi8023** [casatwy/CTMediator#33]
背景：
项目语言swift，直接在项目文件下创建了业务模块,创建了target extension文件夹,kCTMediatorParamsKeySwiftTargetModuleName参数传入的是target所在的文件夹名字,使用的时候因为target为nil导致controller为nil，闪退。
有尝试过将demo中的A_swift文件夹放入demo项目中也出现闪退。
疑问：
swift项目中想使用CTMediator使用必须将业务模块做成cocoapods库才可以？
如果必须做成cocoapods库，那么开发的时候如何直接使用CTMediator？

**Comment by casatwy** [comment]
1. kCTMediatorParamsKeySwiftTargetModuleName参数传入的应该是工程的名字
2. 使用CTMediator并不是必须将业务模块做成cocoapods库，但最好是要做成cocoapods库
3. 如果开发的时候做成cocoapods库，在podspec和podfile文件里把CTMediator带上就行

**Comment by DanielXinYi8023** [comment]
感谢解答。我发现自己在理解的时候也有偏差。

**Comment by dimosz** [comment]
@casatwy 遇到和楼上同样的问题。如果不把业务模块做成单独的工程，直接在主工程中使用 CTMediator，如何设置 kCTMediatorParamsKeySwiftTargetModuleName 才能让项目跑起来？
