### ISSUE TITLE
请教一个问题：事件如何外向传递

### ISSUE THREAD

**Issue by ylxieg** [casatwy/CTMediator#38]
#11 感觉有点类似这个问题
就是业务A中的事件如何传递到主工程中去响应？
业务A对应TargetA。业务A点击事件可以通过通知传递到TargetA中。但是业务A对应的CTMediator_A 如何在主工程中接收响应呢？ 
求指教

**Comment by ylxieg** [comment]
还是不在主工程中交互。A依赖B就拿到B的CTMediator_B来处理？

**Comment by casatwy** [comment]
用block

**Comment by sytuzhouyong** [comment]
如果你想直接调用业务B的方法，可以在调用的地方将CTMediator_B对应的category 头文件 import 进来；如果你不想 import 头文件，可以用 CTMediator 的 performTarget 方法直接调用。 不知道我理解的对不对

**Comment by casatwy** [comment]
他说的是回调

在调用的时候给到一个block来做回调比较好
