### ISSUE TITLE
怎么看不懂为啥这句能弹窗alert窗口？

### ISSUE THREAD

**Issue by jj89757hhb** [casatwy/CTMediator#41]
[[CTMediator sharedInstance] CTMediator_showAlertWithMessage:@"casa" cancelAction:nil confirmAction:^(NSDictionary *info) {
            // 做你想做的事
        }];

**Comment by casatwy** [comment]
因为你是有办法在任意对象中获取App当前正在展示的ViewController的

**Comment by jj89757hhb** [comment]
我是说封装的代码没看到控件alert
