### ISSUE TITLE
是不是模块公开的API接口都要求必须带上参数的？

### ISSUE THREAD

**Issue by AssassinZF** [casatwy/CTMediator#43]
// generate action
    NSString *actionString = [NSString stringWithFormat:@"Action_%@:", actionName];

这句代码是不是限制了被调用者的接口必须要带参数？因为actionString方法名后面的冒号是会一直存在的

**Comment by casatwy** [comment]
是的，没参数传nil不要紧，action实现的时候不去管参数就可以了

发自我的 iPhone

在 2019年3月22日，下午2:31，峰子 <notifications@github.com<mailto:notifications@github.com>> 写道：


// generate action
NSString *actionString = [NSString stringWithFormat:@"Action_%@:", actionName];


这句代码是不是限制了被调用者的接口必须要带参数？因为actionString方法名后面的冒号是会一直存在的
