### ISSUE TITLE
methodSignatureForSelector 获取问题nil 问题？必现

### ISSUE THREAD

**Issue by xrefLee** [casatwy/CTMediator#46]
NSMethodSignature* methodSig = [target methodSignatureForSelector:action];
第一次：在 tagetA 中创建一个方法A 组件化调用 methodSig 正常获取，
第二次：修改tagetA中方法 A的名字，修改 action 字符串名称之后，运行 methodSig返回 nil，重启 xcode之后 methodSig可以正常获取。
环境 xcode10.2

**Comment by casatwy** [comment]
你编译之前clean一下有效么？

**Comment by casatwy** [comment]
而且你的target-action所在的pod有没有重新pod update过？

**Comment by xrefLee** [comment]
clean 之后也不可以，没有用私有库，我就是用你这个 demo 中修改的tagetA中方法 A的名字，是 xcode 的 bug？ 重启 xcode 之后就返回正常了
