### ISSUE TITLE
为什么要用performTarget方法?

### ISSUE THREAD

**Issue by Adrift001** [casatwy/CTMediator#47]
为什么要在Mediator分类方法里面调用performTarget方法呢?直接new一个类返回不就行了?求解释.

**Comment by casatwy** [comment]
new一个类是容易，但你怎么知道这个类都有哪些方法？

为了要解决这个问题，于是你就引入了protocol，或者类的声明。

那响应者和调度者的命名域无法分开了。

发自我的 iPhone

在 2019年4月17日，05:13，发抖喵小咪 <notifications@github.com<mailto:notifications@github.com>> 写道：


为什么要在Mediator分类方法里面调用performTarget方法呢?直接new一个类返回不就行了?求解释.

**Comment by Adrift001** [comment]
我自己写的怎么不知道有什么方法了?即使是别人写的,我也可以点击去看一下源码呐.
