### ISSUE TITLE
Unable to find a pod with name, author, summary, or description matching `CTMediator`

### ISSUE THREAD

**Issue by litt1e-p** [casatwy/CTMediator#5]
@casatwy hi, there is an error occured when I using `pod search CTMediator` and I have updated my pod libs. I don not know why. did I using it in wrong way?

**Comment by casatwy** [comment]
cd ~/.cocoapods/repos/master/ && git pull origin master

**Comment by litt1e-p** [comment]
git shows: `Already up-to-date.` and I can install `CTMediator` via `pod 'CTMediator'`, `pod search` maybe not work in macOS sierra?

**Comment by casatwy** [comment]
my os is macOS Sierra, and it works fine.

<img width="629" alt="2016-11-28 10 40 09" src="https://cloud.githubusercontent.com/assets/1005781/20654756/1d489e98-b557-11e6-9031-90c4c8ad466a.png">

**Comment by litt1e-p** [comment]
@casatwy my pod version: `1.1.0.beta.2`, maybe it is too old?

**Comment by casatwy** [comment]
maybe, my cocoapod's version is 1.1.1

**Comment by litt1e-p** [comment]
@casatwy ok. I should try to upgrade it, thanks!
