### ISSUE TITLE
回调

### ISSUE THREAD

**Issue by cityleaf** [casatwy/CTMediator#55]
你好，跳到新的页面之后，如果需要回调上个页面，如何回调呢？还是从前一个页面params里传一个block到新页面？

**Comment by casatwy** [comment]
是的，把回调做成block塞到参数里发起调用

**Comment by cityleaf** [comment]
> 是的，把回调做成block塞到参数里发起调用
我考虑字典传block存在释放和拷贝问题，所以我目前给UIViewController写了一个类别，扩展属性：
<img width="708" alt="截屏2020-01-03上午11 55 09" src="https://user-images.githubusercontent.com/15885391/71706531-66fe6280-2e20-11ea-85e1-75cb82a2c3d3.png">
有需要回调的页面就实现block
