### ISSUE TITLE
target_action里面dalegate需要return值, 这个值如何传呢.

### ISSUE THREAD

**Issue by xiaoyao20084321** [casatwy/CTMediator#57]
比如, 我在target_action里面对JXCategoryView进行了在封装, 遵循了JXCategoryView代理,  代理需要return值, 这个值是如何传的呢,  我现在是在target_action定义了一个属性来接收了,并且在外界调用shouldCacheTarget:YES  ,并且外界进行持有这个target, 在dealloc里面销毁,  请问这样做对嘛?
![image](https://user-images.githubusercontent.com/10344550/72498060-33342b80-3869-11ea-8071-c0334cd2f69b.png)
![image](https://user-images.githubusercontent.com/10344550/72498078-46df9200-3869-11ea-927d-f39324b07336.png)
![image](https://user-images.githubusercontent.com/10344550/72501167-1d2a6900-3871-11ea-8cae-5a88cd23a35d.png)
![image](https://user-images.githubusercontent.com/10344550/72501197-33d0c000-3871-11ea-9540-7a013bffb8fa.png)

**Comment by casatwy** [comment]
这么做没啥问题，shouldCacheTarget设计来就是想要处理这种应用场景的。

**Comment by xiaoyao20084321** [comment]
哇, 没想到大佬这么快就回复了,  感谢大佬.经过看大佬的文章摸索, 终于成功的自己弄了一个组件,
但是现在还有两个问题没弄明白,  
1.就是您的在现有工程中实施基于CTMediator的组件化方案文章中, 发版时要先执行git add.  git commit  git tag 等等, 最后在执行./upload.sh,  可是我在打开upload.sh文件时候, 发现里面已经写了git add 等等,   是否 我发版时候 只需要执行./upload.sh,就可以了
2, 我看发版时候git commit 的是版本号,  可是这样不就会导致没有发版说明了嘛. 我理解的git commit 应该是发版说明啊, 
以上, 再次感谢大佬.

**Comment by casatwy** [comment]
这两个问题其实是同一个问题。

你先commit一次写入版本说明，然后再跑upload.sh就好了，就是写两遍commit呗，第一次是自己写的版本说明，第二次是脚本写的版本。

**Comment by xiaoyao20084321** [comment]
好的, 谢谢大佬, 原来是我自己误解了.. 我看文章以为第一次commit就要写版本号.尴尬
![image](https://user-images.githubusercontent.com/10344550/72503292-51545880-3876-11ea-8aa9-a496f01e3f42.png)
