### ISSUE TITLE
NSClassFromString 获取pod库里面的类时，返回nil

### ISSUE THREAD

**Issue by asomeLiao** [casatwy/CTMediator#59]

**Comment by casatwy** [comment]
不可能啊，调用代码放上来看看？

**Comment by asomeLiao** [comment]
是这样的，我的podfile用了use_frameworks！ 发现有一些库找不到类，我查了下[NSBundle allFrameworks]找到对应的framework中确实没有找到对应的类，现在我全部改成静态库了。
