### ISSUE TITLE
关于编译问题

### ISSUE THREAD

**Issue by philCc** [casatwy/CTMediator#62]
你好，我最近也在研究组件化，但是发现一个问题，想咨询一个大佬
就是业务拆分成私有pod之后，在开发过程中，每次都需要clean然后重新编译才能看到修改的效果，这个问题该怎么解决呢？

**Comment by casatwy** [comment]
有的时候确实是会这样的，我们也遇到了。好在我们每一个组件都很小，clean完了编译一下几十秒，所以就没太care这个事情。

**Comment by philCc** [comment]
所以，如果遇到大型项目，而且依赖比较多的话，组件化根本不现实对吗？

**Comment by casatwy** [comment]
遇到大型项目才需要组件化啊，一个项目组件化之后500-600个组件很正常。

组件化就是在用很多个小组件构建一个复杂的大工程。

**Comment by philCc** [comment]
如果依赖的第三方库又比较多呢？
每次编译，都需要先clean，第三方库都重新编译一下+组件重新编译
感觉比较耗时啊

**Comment by philCc** [comment]
当然，如果第三方库，不用pod集成的话，应该会快一点吧

**Comment by casatwy** [comment]
你要明白，在组件化场景下做开发的时候，你开发的是组件啊，一个组件最多也就依赖那么几个pod。

而且你是在独立的组件工程里开发组件，不是在大工程里开发组件，编译耗时非常短啊，一个组件才多一点代码？

**Comment by casatwy** [comment]
你不用pod集成的话，那连组件化的门都没入。不管业界什么样的组件化方案，cocoapods私有pod的方式管理组件都是一样的。

**Comment by philCc** [comment]
所以，问题还是在于，开发的时候，还是只通过子组件的demo工程进行调试，而不是运行主工程进行调试对吗？

**Comment by casatwy** [comment]
是的，运行主工程进行调试的时候一般是在测试包已经生成了，然后QA提了bug，然后排查bug的时候才会运行主工程。

绝大多数情况都是在各自的组件工程里做开发做调试的。

**Comment by philCc** [comment]
原来我是陷入了一个误区
谢谢
