### ISSUE TITLE
你好我想问下组件 A 和 A_Category 是不是可以放在同一个私有 pod 库里？

### ISSUE THREAD

**Issue by xxxIxxxx** [casatwy/CTMediator#67]
组件 A 和 A_Category 在都是同一个人或同一个团队维护的情况下。

这种情况多吗？

因为我觉得 A_Category 的维护者要提需求给到 A 的维护者，
然后 A 的维护者再在 Action 内增加暴露的方法。 

这样不如直接交给 A 的维护者来维护 A_Category， 然后就直接放在一个私有 pod 里。

这样理解对吗？希望能够帮忙解答一下，谢谢！

**Comment by casatwy** [comment]
本来就应该是A的维护者来维护A_Category。
A和A_Category是两个pod。

因为A_Category的意义是来告诉别人怎么使用A，所以维护A的人有义务把A_Category维护好。

**Comment by xxxIxxxx** [comment]
> 因为A_Category的意义是来告诉别人怎么使用A

明白了，谢谢大佬！
