### ISSUE TITLE
业务权限问题

### ISSUE THREAD

**Issue by zhfwch** [casatwy/CTMediator#68]
如果遇到有权限问题应该怎么处理？
比如某个业务需要登录，那么返回业务的viewcontroller会延迟返回，还是不返回？业务需要自己处理权限问题吗？
谢谢！

**Comment by casatwy** [comment]
这种情况看产品需求吧

我们这边的处理方式是如果进入了需要登陆的模块，就会立刻唤起登录页面，登陆成功之后就进入。点了取消或登录失败，就啥也不做，用户还停留在之前的页面。

**Comment by zhfwch** [comment]
还有一个问题需要您帮忙解答一下：url通过route远程调用，跳转页面。
url（未登录）--->route--->CTMediator--->B模块（需要登录）
这个时候登录是由B模块处理还是route处理呢？谁处理比较合理一些

谢谢！

**Comment by casatwy** [comment]
这时候让B模块处理，因为B模块知道自己是否需要登陆态。

CTMediator不需要知道这么细节的东西，它也不应该知道。

展示页面时，不是让B模块返回一个ViewController出去的，而是直接就在B模块中调用CTMediator的方法直接push或者present页面了。

具体的方法在这里：
https://github.com/casatwy/CTMediator/blob/master/CTMediator/CTMediator/CTMediator%2BHandyTools.h

**Comment by zhfwch** [comment]
好的。谢谢！
我看到这里第57行，有外部处理present还是push，所以比较疑惑。
https://github.com/casatwy/CTMediator/blob/master/CTMediator/ViewController.m

CTMediator中safePerformAction:(SEL)action target:(NSObject *)target params:(NSDictionary *)params方法，处理了一些基本类型，如果再增加一个方法，入参多一个void *value，专门处理基本类型会不会好一点。另外如果以后强制使用Swift但是Swift又没有runtime，好像不太好应对。当然强制使用Swfit，这个不太可能。

**Comment by casatwy** [comment]
demo里面的是让外部处理的，那个category是我后来加的。

我现在的工程就是swift，是可以用的。而且有的组件纯oc，有的组件纯swift，也是可以共存的。

void那块我们理解你的意思

**Comment by zhfwch** [comment]
- (id)safePerformAction:(SEL)action target:(NSObject *)target params:(NSDictionary *)params
{
    NSMethodSignature *methodSig = [target methodSignatureForSelector:action];
    NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:methodSig];
    [invocation setSelector:action];
    [invocation setTarget:target];
    [invocation invoke];
    void *result;
    [invocation getReturnValue:&result];
    return (__bridge id)(result);
}

- (void)safePerformAction:(SEL)action target:(NSObject *)target params:(NSDictionary *)params value:(void *)value
{
    NSMethodSignature *methodSig = [target methodSignatureForSelector:action];
    NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:methodSig];
    [invocation setSelector:action];
    [invocation setTarget:target];
    [invocation invoke];
    [invocation getReturnValue:value];
}
第一个方法只处理id类型（或者无返回值），第二个方法辅助处理基本类型

**Comment by casatwy** [comment]
我这边不考虑swift不能引用oc的情况，我觉得近期也不会出现这样的情况

返回类型如果引入void的话，就会导致动态调度的时候，你不知道实现这个Action的人用的是void返回还是id，就不知道这次调用要不要给个参数来接返回的内容，就很难处理。所以我设计的时候就只允许一种返回，就是id，每个调用都会接返回，无非就是接了用不用而已。

而且swift下也可以用let _ = xxxx()这种方式来处理没有返回的调用。

**Comment by zhfwch** [comment]
我的意思是现在是通过@encode来判断是否基本类型然后单独处理返回值，但是基本类型比较多，那safePerformAction就需要处理所有的基本类型，否则就会crash。所以我的想法是一个函数只处理id，另一个函数只处理基本类型。如果说能约定返回值只允许id，那皆大欢喜。

**Comment by casatwy** [comment]
嗯？现在是哪个crash了么？我记得我测过，没有crash啊

**Comment by zhfwch** [comment]
如果target-action中action的返回值类型是CGSize，那么就会crash吧。现在safePerformAction方法里支持void、nsinteger、bool、float、nsuinteger。target-action中的action返回值每多一种基本类型，都要修改safePerformAction。

**Comment by casatwy** [comment]
CGSize这种是会crash的，首先它已经不是基本类型了，它已经是struct了。

另外，虽然它是系统定义的struct，但这种struct类型无法穷举，且是可被其它基本类型替代的。
所以这边并不打算考虑支持它。

总之，可能在你的定义标准里，会把系统库里面定义的struct也定义为“基础类型”。
但在CTMediator看来，它是个struct，已经不是基础类型了。

**Comment by zhfwch** [comment]
好的。非常感谢您
