### ISSUE TITLE
请教一个硬编码的问题

### ISSUE THREAD

**Issue by snilwx** [casatwy/CTMediator#69]
在Category中将常规参数打包成字典，在Target处再把字典拆包成常规参数，拆包的过程中造成了一部分的硬编码。有没有什么办法避免硬编码？

**Comment by casatwy** [comment]
你搞错了，CTMediator之所以有category，就是为了缩小硬编码问题。

在没有category的时候，硬编码散落在业务。
有了category之后，硬编码就仅限于category了。

业界组件化方案中，没有一个是没有硬编码问题的。
