### ISSUE TITLE
你好，我在swift下用这个框架发现类的时候一直找不到target

### ISSUE THREAD

**Issue by cxq1221** [casatwy/CTMediator#7]
请问是我的代码有什么错误吗~一直没搞好，本来工程构建到一半卡住了

调用：`override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        let vc = CTMediator.sharedInstance().performTarget("T", action: "test", params: nil, shouldCacheTarget: false)
        navigationController!.pushViewController(vc! as! UIViewController, animated: true)
    }`

target：`class Target_T_: NSObject {
    func Action_test(params: [AnyHashable : Any]) -> UIViewController {
        return UIViewController()
    }
}`

**Comment by casatwy** [comment]
https://github.com/ModulizationDemo/SwfitDemo

你看一下这个。

另外，你需要建立一个私有库：
pod repo add PrivatePods https://github.com/ModulizationDemo/PrivatePods.git

然后 pod update 就可以跑SwiftDemo了

**Comment by cxq1221** [comment]
您好，按照您Demo里的，我如果目标组件化出来的代码也是swift写的，必须使用OC写的分类以及相应的Target_Action文件吗
上次提的issue我只是测试了一下能否使用CTMediator直接找到swift的类及方法

**Comment by casatwy** [comment]
CTMediator我修改了一下，现在是满足你的要求了。我上传了一个[A_swift](https://github.com/ModulizationDemo/A_swift)，这就是一个swift的组件，同时它的target也是由swift写成的。
