### ISSUE TITLE
关于组件化时重复引入基础库的问题？

### ISSUE THREAD

**Issue by snilwx** [casatwy/CTMediator#70]
请教您一个关于组件化时重复引入基础库的问题，场景是这样的：

有四个功能模块，分给了四个不同的团队开发，我们只负责整合集成组件并打包成最终的APP，四个组件都是以framework的形式提供给我们的，我们这边看不到组件源码，这四个组件都会依赖相同的基础库和网络请求库，那么他们打包成framework的时候，每个framework里都会包含这些基础库和网络请求库，那么我们在最终整个这四个功能组件的时候，基础组件相当于被项目引入了4次？这样理解对吗？如果对的话，有什么方法能解决呢？

**Comment by charlesYun** [comment]
不会，很简单就能解释，假设你自己项目用了某个pod库里面引用了sdwebimage，同时你自己项目也用了sdwebimage，实际上你看下你pod文件下面有几个sdwebimage呢？
