### ISSUE TITLE
CTMediator不维护了吗? 

### ISSUE THREAD

**Issue by shi1234ww** [casatwy/CTMediator#72]
你好, 根据
https://casatwy.com/modulization_in_action.html
这篇文章里的操作步骤

5.将ConfigPrivatePod的template文件夹下Podfile中source 'https://github.com/ModulizationDemo/PrivatePods.git'改成第一步里面你自己的私有Pod源仓库的repo地址
6.将ConfigPrivatePod的template文件夹下upload.sh中PrivatePods改成第二步里面你自己的私有Pod源仓库的名字

,  目前到这里都走不下去了 ...
1. Podfile中  没有,   source 'https://github.com/ModulizationDemo/PrivatePods.git'
2.ConfigPrivatePod的template文件夹下upload.sh中 没有这个 PrivatePods

**Comment by casatwy** [comment]
主要是现在ConfigPrivatePods跟当初写的文章不一样了。

5.将ConfigPrivatePod的template文件夹下Podfile中source 'https://github.com/ModulizationDemo/PrivatePods.git'改成第一步里面你自己的私有Pod源仓库的repo地址
6.将ConfigPrivatePod的template文件夹下upload.sh中PrivatePods改成第二步里面你自己的私有Pod源仓库的名字

上面这两步的目的是让你的工程使用你自己创建的私有组件索引库，不必拘泥于例
