### ISSUE TITLE
请教为什么每个业务提供以独立repo形式提供Category

### ISSUE THREAD

**Issue by ticsmatic** [casatwy/CTMediator#77]
是否可以将Category以子pod的形式合并在同一个pod里，方便统一查阅管理。
此时业务提供方A维护pod下A的分类子库（子库CTMediator+A）
此时业务提供方B维护pod下B的分类子库（子库CTMediator+B）

这样做有什么弊端吗

**Comment by casatwy** [comment]
你想这么做也可以

**Comment by ticsmatic** [comment]
好的，多谢
