### ISSUE TITLE
关于组件之间的互相调用和组件生命周期

### ISSUE THREAD

**Issue by selectersky** [casatwy/CTMediator#8]
## 场景
* 组件管理库M 包含`CTMediator`
* 组件A和组件B，它们相互独立并在不同的仓库。M能知道组件A和组件B，但是默认情况下，组件A和组件B并不知道M

## 需求
1. 组件A和组件B如何互相调用？或如何通过M来通信？
1. 如果组件A和组件B都有生命周期：如初始化、登录、退出、反初始化，该如何实现？

麻烦大神解答，非常感谢。

<mark>说明：</mark> 组件A和组件B如何互相调用， 尽量不要考虑组件都包含CTMediator的情况。因为这样的话，写一个头文件协议是不是更简单？  
另外，组件A和组件B只是方便说明，这里要考虑的情况就是有很多个组件，至少具体多少个也只是程序运行后才知道的。

**Comment by selectersky** [comment]
<mark>说明：</mark> 组件A和组件B如何互相调用？ 尽量不要考虑都包含CTMediator的情况。因为这样的话，写一个头文件协议是不是更简单？

**Comment by casatwy** [comment]
1. 要想在跨命名域的情况下进行跨业务调用，脱离中间人是做不到的。唯一可以考虑的是使用框架现有的已经跨命名域的对象或机制来做中间人。这个对象可以是NSNotificationCenter，机制可以是文件机制或者socket机制。

在CTMediator的场景下，A调用B时，B是不需要依赖CTMediator的。在B调用A时，A是不需要依赖CTMediator的。但如果A和B互相都要调用，那么A和B就都需要依赖CTMediator了。

2. 生命周期的场景我需要一个明确的业务场景描述，才能说如何实现。

例如A组件的生命周期是全工程可见，还是部分关心的人可见？以及在生命周期的每个阶段的事件切片中，是否会存在外来事件的插入？

在不考虑上面问题的情况下，单就生命周期来看，CTMediator并不要求组件常驻内存。因此，初始化和反初始化的管理取决于Action如何实现。组件中的某个对象可能常驻内存，但组件整体是不应该常驻内存的，如果你认为有某个组件需要整体常驻内存，请向我说明业务场景。

自动登陆和退出的机制我现在默认为你是说的用户的登录和退出。这其实是由网络层管理的，它能够做到未登录情况下访问需要登陆态的页面或API时，网络层会通过CTMediator自动唤起登陆流程，唤起登陆流程之后，此时全工程就已经进入登录态了，任何其他的组件再访问类似的页面和API时，就都不会唤起登陆流程了。登陆流程结束之后，网络层会继续调用之前因缺失登陆态而挂起的API或页面。

**Comment by casatwy** [comment]
另外，如果你选择使用头文件协议的话，就做不到A调用B时，B不依赖头文件协议了。

**Comment by selectersky** [comment]
@casatwy 感谢回复 ：-）

关于中间人：这里有考虑有加入中间人M，如上内容所述。这时，通过中间人M来实现组件A和组件B的相互通信，有好的解决方案吗？

关于生命周期场景，当上层UI进入登录页面、登录成功进入主页、退出登录再进入页面时，都要告知下所有的组件（如果组件有需要知道的话。这里的组件可能是个具体的UI，也有可能是一个单例，或可以理解这个组件在登录或退出时，要告诉和组件通信的服务器一声）

**Comment by casatwy** [comment]
1. 没有更好的了

2. 使用NSNotification是最经济有效的做法
