### ISSUE TITLE
远程调用 Swift 响应者问题

### ISSUE THREAD

**Issue by Andy0570** [casatwy/CTMediator#80]
```swift
// Target_social.swift
@objc class Target_social: NSObject {
    @objc func Action_mainPage(_ params: NSDictionary) -> UIViewController {
        return SocialViewController()
    }
}
```

通过 Schema URL 方式调用 Swift 响应者时，URL 需要设置为：`schema://social/mainPage?kCTMediatorParamsKeySwiftTargetModuleName=ApplicationName`，请问该如何优化实现不需要传递 `kCTMediatorParamsKeySwiftTargetModuleName` 参数？

**Comment by casatwy** [comment]
因为走的是runtime调度，Swift的Target必须要带上module name才可以的。除非你保证target的name和module的name是一致的，那么外面就可以少传一个，但是内部调用的时候，module name还是要给的。你可以做个demo验证一下。

**Comment by casatwy** [comment]
目前看你这个工程似乎是个单体工程，所以你的modulename是你的Application Name，如果将来是多组件工程的话，这个module name就是那个组件名了，不是application name了。
